name: CI/CD DevOps Final

on:
  push:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker
        run: docker buildx build --load --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/app-hola-devops:latest ${{ github.workspace }}

      - name: Push imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/app-hola-devops:latest

      - name: Deploy a Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
